const fs=require('fs'),vm=require('vm'),path=require('path');
const html=fs.readFileSync(path.join(__dirname,'..','preview.html'),'utf8');
const code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const store=new Map();
const localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const listeners={};
const app={innerHTML:'',listeners:{},addEventListener:(n,fn)=>listeners[n]=fn};
const toast={textContent:'',classList:{add(){},remove(){}}};
const document={getElementById:id=>id==='app'?app:id==='toast'?toast:null};
const location={origin:'http://test.local',pathname:'/preview.html',hash:'#/business'};
const window={addEventListener:(n,fn)=>listeners['window:'+n]=fn,open(){}};
class FD{constructor(form){this.fields=form.fields||{}}get(k){return this.fields[k]??null}}
const context={console,document,window,location,localStorage,navigator:{},URL,URLSearchParams,TextEncoder,FormData:FD,setTimeout:()=>1,clearTimeout(){},Blob,XMLSerializer:function(){},prompt(){}};
vm.createContext(context);vm.runInContext(code,context);
const click=(action,dataset={})=>listeners.click({target:{closest:s=>s==='[data-scroll]'?null:s==='[data-action]'?{dataset:{...dataset,action}}:null}});
const submit=(id,fields)=>listeners.submit({target:{id,fields},preventDefault(){}});
const hash=(v)=>{location.hash=v;listeners['window:hashchange']();};
function check(cond,msg){if(!cond)throw new Error(msg)}
check(app.innerHTML.includes('Grow your food business'), 'seller gate should require buyer signin');
click('open-signin');
click('switch-account-mode',{mode:'request'});
submit('request-account-form',{name:'Ada Lovelace',email:'ada@example.com'});
let accounts=JSON.parse(store.get('juniper.v2.accounts'));
check(accounts.length===1&&accounts[0].role==='buyer'&&accounts[0].approved===true,'buyer account should be active immediately');
check(JSON.parse(store.get('juniper.v2.user')).role==='buyer','new user should be signed in as buyer');
click('request-seller');
check(app.innerHTML.includes('Apply for seller mode'),'seller application form should render');
check(app.innerHTML.includes('name="legalName"')&&app.innerHTML.includes('name="businessAddress"')&&app.innerHTML.includes('name="passportPhoto"')&&app.innerHTML.includes('name="profilePhoto"'),'seller application should request legal name, address, and both photo fields');
check(app.innerHTML.includes('not uploaded or saved')&&app.innerHTML.includes('Seller approval remains disabled'),'preview must disclose local-only photos and keep approval gated');
submit('seller-application-form',{legalName:'Ada Lovelace',storeName:'Ada Kitchen',businessAddress:'12 Allen Avenue',location:'Lagos',phone:'+2348012345678',whatsapp:'',latitude:'6.52',longitude:'3.38',deliveryRadiusKm:'25',bio:'Fresh soups and rice'});
check(!store.has('juniper.v2.seller-applications'),'application should reject missing image selections');
submit('seller-application-form',{legalName:'Ada Lovelace',passportPhoto:{name:'sample-passport.jpg',size:1024,type:'image/jpeg'},profilePhoto:{name:'sample-profile.jpg',size:1024,type:'image/jpeg'},storeName:'Ada Kitchen',businessAddress:'12 Allen Avenue',location:'Lagos',phone:'+2348012345678',whatsapp:'',latitude:'6.52',longitude:'3.38',deliveryRadiusKm:'25',bio:'Fresh soups and rice'});
const savedApplication=JSON.parse(store.get('juniper.v2.seller-applications'))[0];
check(savedApplication.legalName==='Ada Lovelace'&&savedApplication.businessAddress==='12 Allen Avenue'&&savedApplication.secureFilesReceived===false,'text details should be recorded as a local application without claiming file receipt');
check(!JSON.stringify(savedApplication).includes('sample-passport.jpg')&&!JSON.stringify(savedApplication).includes('sample-profile.jpg'),'selected file metadata/content must not be persisted');
check(JSON.parse(store.get('juniper.v2.user')).role==='buyer','pending application must not switch mode');
check(app.innerHTML.includes('awaiting verification')&&app.innerHTML.includes('continue ordering'),'pending screen should preserve buyer access');
hash('#/menu?table=08&s=juniper');
check(app.innerHTML.includes('Classic Nigerian Chapman')&&app.innerHTML.includes('Kunu Aya')&&app.innerHTML.includes('Sparkling lemon soda'),'menu should include Nigerian and international soft drinks');
click('add',{id:'suya-bowl'}); click('checkout'); hash(location.hash);
check(app.innerHTML.includes('Review your order'),'pending buyer should reach checkout');
click('place-order'); hash(location.hash);
check(JSON.parse(store.get('juniper.v2.orders')).length===1,'pending buyer should be able to place an order');
check(JSON.parse(store.get('juniper.v2.user')).role==='buyer','ordering must not change pending buyer mode');
hash('#/store/juniper');
check(app.innerHTML.includes('Tag this seller')&&app.innerHTML.includes('<circle cx="12" cy="9.5"'),'seller profile should offer customer tags using the award mark');
click('toggle-seller-tag',{id:'juniper'});
check(JSON.parse(store.get('juniper.v2.customer-tags'))['ada@example.com'].includes('juniper'),'customer tag should be stored for buyer');
hash('#/updates');
check(app.innerHTML.includes('Juniper Kitchen')&&app.innerHTML.includes('No menu updates yet'),'updates page should show tagged sellers');
hash('#/admin');
check(app.innerHTML.includes('Ada Kitchen')&&app.innerHTML.includes('Verification required'),'admin should show app but block seller approval');
click('approve-seller',{index:'0'});
accounts=JSON.parse(store.get('juniper.v2.accounts'));
check(accounts[0].role==='buyer'&&JSON.parse(store.get('juniper.v2.seller-applications')).length===1,'seller cannot be activated without secure identity verification');
click('deny-seller',{index:'0'});
check(JSON.parse(store.get('juniper.v2.seller-applications')).length===0&&JSON.parse(store.get('juniper.v2.user')).role==='buyer','declining application must leave buyer account active');
console.log('Buyer signup/order, seller-verification guard, customer tags, menu updates page, and expanded drinks passed.');
