const fs=require('fs'),vm=require('vm'),path=require('path');const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');const code=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const store=new Map();const buyer={name:'Sam Buyer',email:'sam@example.com',role:'buyer',approved:true};const other={name:'Lee Customer',email:'lee@example.com',role:'buyer',approved:true};
for(const[k,v]of Object.entries({'juniper.v2.user':buyer,'juniper.v2.accounts':[buyer,other]}))store.set(k,JSON.stringify(v));
const localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};const listeners={};const app={innerHTML:'',addEventListener:(n,f)=>listeners[n]=f};const toast={textContent:'',classList:{add(){},remove(){}}};const document={getElementById:id=>id==='app'?app:id==='toast'?toast:null};const location={origin:'https://x',pathname:'/index.html',hash:'#/rider-apply'};const window={addEventListener:(n,f)=>listeners['window:'+n]=f,open(){}};class FD{constructor(x){this.f=x.fields||{}}get(k){return this.f[k]??null}};const sandbox={console,document,window,location,localStorage,navigator:{},URL,URLSearchParams,TextEncoder,FormData:FD,setTimeout:()=>1,clearTimeout(){}};vm.createContext(sandbox);vm.runInContext(code,sandbox);const click=(action,dataset={})=>listeners.click({target:{closest:s=>s==='[data-action]'?{dataset:{...dataset,action}}:null}});const submit=(id,fields)=>listeners.submit({target:{id,fields},preventDefault(){}});const hash=v=>{location.hash=v;listeners['window:hashchange']()};function check(v,m){if(!v)throw Error(m)}
check(app.innerHTML.includes('rider-application-form'),'rider application form shown');
submit('rider-application-form',{name:'Sam Dispatch',phone:'+2348011112222',whatsapp:'+2348011112222',vehicle:'Motorcycle',serviceArea:'Ikeja',latitude:'6.60',longitude:'3.35',serviceRadiusKm:'20',baseFee:'1000'});
check(JSON.parse(store.get('juniper.v2.rider-applications')).length===1,'rider application queued');hash('#/admin');check(app.innerHTML.includes('Sam Dispatch')&&app.innerHTML.includes('Approve rider'),'admin sees rider application');click('approve-rider',{index:'0'});
let accounts=JSON.parse(store.get('juniper.v2.accounts'));const riderAcct=accounts.find(x=>x.email==='sam@example.com');check(riderAcct.riderId&&riderAcct.role==='buyer','rider approval should preserve buyer mode');
const riderId=riderAcct.riderId;check(JSON.parse(store.get('juniper.v2.riders'))[riderId].active,'approved rider is active');hash('#/rider');check(app.innerHTML.includes('Assigned deliveries')&&app.innerHTML.includes('Sam Dispatch'),'rider dashboard active');
click('sign-out');click('open-signin');submit('signin-form',{email:'lee@example.com'});hash(`#/rider-profile/${riderId}`);check(app.innerHTML.includes('Tag rider')&&app.innerHTML.includes('Rate this delivery person'),'public rider page supports tagging and reviews');click('toggle-rider-tag',{id:riderId});
submit('rider-review-form',{riderId,rating:'5',comment:'Quick and careful delivery'});check(JSON.parse(store.get('juniper.v2.rider-tags'))['lee@example.com'].includes(riderId),'rider tag saved');check(JSON.parse(store.get('juniper.v2.rider-reviews'))[riderId].length===1,'rider review saved');console.log('Rider application review, activation, public profile, tag, and rating passed.');
